name: Run Script with ads on Push and Daily Schedule

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  run-script:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: Install the 'ads' library
      run: |
        pip install --upgrade pip
        pip install ads PyYAML numpy

    - name: Run the script
      run: |
        python scripts/get_ads.py  # Replace with the path to your script file
      env:
          ADS_DEV_KEY: ${{secrets.ADS_DEV_KEY}}
    - name: Set Git Configuration
      run: |
        git config --global user.email 'juan.guerra@yale.edu'
        git config --global user.name 'jguerra-astro'

    - name: Pull Latest Changes
      run: git pull origin master

    - name: Check for changes
      id: git-check
      run: |
        git add -A
        git diff --staged --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and Push Changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git add scripts/most_recent_all.bib
        git commit -m "updating bib file"
        git push origin master